server:
  port: 8080

spring:
  application:
    name: iam
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5434/easy_fold_service}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:password}
    driver-class-name: org.postgresql.Driver
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      idle-timeout: 30000
      max-lifetime: 60000
      register-mbeans: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect
      format_sql: true
      use_sql_comments: true
      generate_statistics: true

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE
    org.springframework.data.repository.config.RepositoryConfigurationExtensionSupport: WARN